import type { Metadata } from "next";
import { Zen_Kaku_Gothic_Antique } from "next/font/google";
import "./globals.css"; // Tailwind CSS の適用

const zenKakuGothicAntique = Zen_Kaku_Gothic_Antique({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "技術ブログ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${zenKakuGothicAntique.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
